#!/bin/sh
#
# Asserts that the module is ready for release with the expected quality

# Rollback modified package.json file so it has the previous version
rollbackPackage() {
    git checkout package.json
}

# Checking that the npm-shrinkwrap.json file is up-to-date wrt to the
# package.json file.
if [ package.json -nt npm-shrinkwrap.json ]
then
    echo "File package.json is newer than file npm-shrinkwrap.json"
    printf "To fix this, run:\nnpm run safefreeze\n\n"

    rollbackPackage
    exit 1
fi
