#!/bin/sh
#
# Asserts that the module is ready for release with the expected quality

# cf. https://docs.npmjs.com/cli/version
new_version=$1

# Rollback modified package.json file so it has the previous version
rollbackPackage() {
    git checkout package.json
}

# Checking the CHANGELOG contains an entry (with right format) for each version.
# The expected format is as follows:
# ## [VERSION]
for entry in $(git tag|cut -c 2-) $new_version
do
    if $(grep --quiet -E "^## \[$entry\]" CHANGELOG.md)
    then
        echo "OK: Entry $entry present in the CHANGELOG.md"
    else
        echo "KO: Entry $entry MISSING in the CHANGELOG.md"

        rollbackPackage
        exit 1
    fi
done
