#!/bin/sh
#
# Asserts that the module is ready for release with the expected quality

# cf. https://docs.npmjs.com/cli/version
new_version=$1

# Rollback modified package.json file so it has the previous version
rollbackPackage() {
    git checkout package.json
}

# Checking the CHANGELOG contains an entry for each version
for entry in $(git tag|cut -c 2-) $new_version
do
    if $(grep -q -E ^$entry CHANGELOG)
    then
        echo "OK: Entry $entry present in the CHANGELOG"
    else
        echo "KO: Entry $entry MISSING in the CHANGELOG"

        rollbackPackage
        exit 1
    fi
done
