#!/bin/sh

# cf. https://docs.npmjs.com/cli/version
new_version=$1

for entry in $(git tag|cut -c 2-) $new_version
do
    if $(grep -q -E ^$entry ChangeLog)
    then
        echo "Entry $entry present in the ChangeLog"
    else
        echo "Entry $entry MISSING in the ChangeLog"
        exit 1
    fi
done